name: Evaluation Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r 05-projects/eval-automation/requirements.txt
          npm install --global promptfoo
      - name: Run evaluations
        env:
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
        run: |
          cd 05-projects/eval-automation
          python run_evals.py --dataset scenarios.csv
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: eval-reports
          path: 05-projects/eval-automation/reports
