name: Seed Issues
on:
  push:
    branches: [ main ]
    paths:
      - .github/seed-issues.json
      - .github/workflows/seed-issues.yml
  workflow_dispatch: {}

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const issues = JSON.parse(fs.readFileSync('.github/seed-issues.json', 'utf8'));
            // Fetch existing open issues
            const existing = await github.paginate(github.rest.issues.listForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });
            const byTitle = new Set(existing.map(i => i.title.toLowerCase()));
            for (const issue of issues) {
              if (byTitle.has(issue.title.toLowerCase())) {
                core.info(`Skip existing: ${issue.title}`);
                continue;
              }
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                body: issue.body,
                labels: issue.labels,
              });
              core.info(`Created: ${issue.title}`);
            }
